import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useState } from 'react';
import Header from 'components/header';
import Footer from 'components/footer';
import CreateForm from '../components/CreateForm';
import CookieStandList from '../components/CookieStandList';

export default function Home() {
    const [cookieStandList, setCookieStandList] = useState([]);

  const handleCookieStandCreate = (cookieStand) => {
    setCookieStandList((prevList) => [...prevList, cookieStand]);
  };

  function cookieStandCreate(event) {
    event.preventDefault();

    const location = event.target.location.value;
    const minCustomersPerHour = parseFloat(event.target.minCustomersPerHour.value);
    const maxCustomersPerHour = parseFloat(event.target.maxCustomersPerHour.value);
    const avgCookiesPerSale = parseFloat(event.target.avgCookiesPerSale.value);

    const cookieStand = {
      location,
      minCustomersPerHour,
      maxCustomersPerHour,
      avgCookiesPerSale,
    };

    setCookieStandList((prevList) => [...prevList, cookieStand]);
  }

  return (
    <div>
      <Head>
        <title>Cookie Stand</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main style={{ display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
        <CreateForm onCookieStandCreate={handleCookieStandCreate} />
        <CookieStandList cookieStandList={cookieStandList} />
      </main>
      <Footer cookieStandCount={cookieStandList.length} />
    </div>
  );
}