import Head from 'next/head';
import { useState } from 'react';
import { useAuth } from '../contexts/auth';
import useResource from '../hooks/useResource';
import Header from 'components/header';
import Footer from 'components/footer';
import CreateForm from '../components/CreateForm';
import CookieStandList from '../components/CookieStandList';
import LoginForm from '../components/LoginForm';

export default function Home() {
    const { user } = useAuth();
    const {resources, loading, createResource, deleteResource} = useResource();

    return (
        <div>
          <Head>
            <title>Cookie Stand Admin</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Header />
          <main style={{ display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
              {user ? (
                  <>
                <CreateForm onCookieStandCreate={createResource} />
                <CookieStandList cookieStandList={resources} loading={loading} onDelete={deleteResource} />
                  </>
                  ) : (
                        <>
                            <LoginForm />
                        </>
                  )}
          </main>
          <Footer />
        </div>
      );
}