import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useState } from 'react';

export default function Home() {
    const [cookieStandList, setCookieStandList] = useState(['Report Table Coming Soon...']);

  function cookieStandCreate(event) {
    event.preventDefault();

    const location = event.target.location.value;
    const minCustomersPerHour = parseFloat(event.target.minCustomersPerHour.value);
    const maxCustomersPerHour = parseFloat(event.target.maxCustomersPerHour.value);
    const avgCookiesPerSale = parseFloat(event.target.avgCookiesPerSale.value);

    const cookieStand = {
      location,
      minCustomersPerHour,
      maxCustomersPerHour,
      avgCookiesPerSale,
    };

    setCookieStandList((prevList) => [...prevList, cookieStand]);
  }

  return (
    <div>
      <Head>
        <title>Cookie Stand</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="flex items-center justify-between p-4 bg-green-600 text-black">
          <h1 className="text-4xl">Cookie Stand Admin</h1>
      </header>
      <main style={{ display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
        <form onSubmit={cookieStandCreate} style={{ marginTop: '3rem', marginBottom: '2' +
                'rem', width: '80%' }}>
          <div
            style={{
              backgroundColor: '#B3E5BE',
              padding: '1rem',
              borderRadius: '0.5rem',
              marginBottom: '1rem',
            }}
          >
            <div style={{ marginBottom: '1rem' }}>
              <h1 style={{ fontWeight: 'bold', textAlign: 'center', marginBottom: '0.5rem', fontSize: '2rem' }}>Create Cookie Stand</h1>
              <div style={{ display: 'flex' }}>
                <label htmlFor="location" style={{ fontWeight: 'bold', flex: '1', display: 'flex', alignItems: 'center' }}>
                  Location
                  <input
                    id="location"
                    name="location"
                    style={{ marginLeft: '0.5rem', width: '100%' }}
                  />
                </label>
              </div>
            </div>
            <div style={{ display: 'flex', marginBottom: '1rem' }}>
              <label htmlFor="minCustomersPerHour" style={{ fontWeight: 'bold', flex: '1', display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
                Minimum Customers per Hour
                <input
                  id="minCustomersPerHour"
                  name="minCustomersPerHour"
                  style={{ marginLeft: '0.5rem', width: 'calc(100% - 5rem)' }}
                />
              </label>
              <label htmlFor="maxCustomersPerHour" style={{ fontWeight: 'bold', flex: '1', display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
                Maximum Customers per Hour
                <input
                  id="maxCustomersPerHour"
                  name="maxCustomersPerHour"
                  style={{ marginLeft: '0.5rem', width: 'calc(100% - 5rem)' }}
                />
              </label>
              <label htmlFor="avgCookiesPerSale" style={{ fontWeight: 'bold', flex: '1', display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
                Average Cookies per Sale
                <input
                  id="avgCookiesPerSale"
                  name="avgCookiesPerSale"
                  style={{ marginLeft: '0.5rem', width: 'calc(100% - 5rem)' }}
                />
              </label>
              <button
                type="submit"
                style={{ backgroundColor: '#379237', color: 'black', padding: '0.5rem', borderRadius: '0.25rem' }}
                >
                Create
              </button>
            </div>
            <div style={{ display: 'flex', justifyContent: 'flex-end' }}>
            </div>
          </div>
        </form>
        <div style={{ marginBottom: '3rem'}}>
          {cookieStandList.length > 0 && (
            <pre>{JSON.stringify(cookieStandList[cookieStandList.length - 1], null, 2)}</pre>
          )}
        </div>
      </main>
      <footer className="p-4 mt-8 bg-green-600 text-black ">
          <nav>
              {/* will build out careers page soon */}
              <a href="careers">2023</a>
          </nav>
      </footer>
    </div>
  );
}